import { useIdioma } from '../i18n/idioma'

const PASOS = [
  ['Verificar el expediente en SIS', 'Verify the SIS record', 'Busca al estudiante asignado y confirma identidad, tutor responsable, programa, institución o hub, estado de matrícula y documentos pendientes. Si faltan datos o el estudiante no está asignado a ti, solicita revisión a coordinación; no lo marques como aprobado.', 'Find your assigned student and check identity, responsible guardian, program, institution or hub, enrollment status and missing documents. Ask coordination to review missing data or assignments; do not mark enrollment approved.', 'Lista de datos verificados y pendientes, con responsable y fecha de revisión.', 'A list of checked and missing information, with owner and review date.'],
  ['Confirmar el plan de acompañamiento', 'Confirm the learning support plan', 'Consulta el diagnóstico y el PEI disponibles. Confirma objetivos, materiales, modalidad, accesos y área asignada. Mentoría no cambia créditos, convalidaciones ni decisiones de admisión; deriva esas decisiones a coordinación y dirección.', 'Review the available assessment and individual learning plan. Confirm goals, materials, delivery format, access and your assigned subject. Refer credit, transfer and admission decisions to coordination and school administration.', 'Plan revisado: objetivo, actividad siguiente, apoyo necesario y responsable.', 'Reviewed plan: goal, next activity, support needed and owner.'],
  ['Preparar y realizar la atención', 'Prepare and deliver support', 'Antes de la sesión revisa la última actividad y su evidencia. Durante la atención pregunta qué comprendió, observa cómo trabaja y adapta el apoyo al objetivo. En inglés y Life Skills utiliza el espacio académico correspondiente de Dual Diploma cuando ese sea su programa; no registres allí una matrícula del SIS.', 'Before the session, review the latest activity and evidence. Ask what the student understood, observe their work and adapt support to the goal. For English and Life Skills, use the relevant Dual Diploma academic area when that is their program; enrollment remains in SIS.', 'Actividad realizada, evidencia observada, dificultad concreta y siguiente paso.', 'Activity completed, observed evidence, specific difficulty and next step.'],
  ['Registrar y verificar el avance', 'Record and verify progress', 'Registra fecha, actividad, resultado observable y próximo compromiso en el sistema correspondiente. Comprueba que el registro aparece en el estudiante correcto. No conviertas asistencia o tiempo conectado en dominio académico, ni una práctica ficticia en avance real.', 'Record date, activity, observable outcome and next commitment in the appropriate system. Check the entry belongs to the correct student. Attendance or time online is not evidence of mastery; practice data is not real progress.', 'Registro guardado y revisado; entrega o evidencia enlazada si corresponde.', 'Saved and checked record, with submission or evidence linked where applicable.'],
  ['Dar seguimiento a la familia', 'Follow up with the family', 'Contacta al tutor por el canal institucional autorizado. Explica un logro, una dificultad y una acción concreta para casa; acuerda quién la hará y cuándo se revisará. En Off-Campus incluye la mentoría mensual. Si no hay respuesta, registra los intentos y solicita apoyo a coordinación; no compartas datos con personas sin autorización.', 'Contact the guardian through an authorized institutional channel. Explain one achievement, one difficulty and a concrete home action; agree an owner and review date. Include monthly mentoring for Off-Campus. Record unanswered contacts and request coordination support; do not disclose data to unauthorized people.', 'Fecha, canal, resumen, acuerdo familiar y próxima revisión.', 'Date, channel, summary, family agreement and next review.'],
  ['Cerrar el ciclo y escalar pendientes', 'Close the loop and escalate', 'En la próxima revisión comprueba si se cumplió el acuerdo y ajusta el apoyo. Coordinación revisa todas las áreas de sus estudiantes, desbloquea pendientes con el responsable y comunica a dirección las decisiones fuera de su alcance. Una incidencia de protección de menores se deriva de inmediato por el protocolo institucional, sin investigar por cuenta propia.', 'At the next review, check the agreement and adjust support. Coordination reviews all areas for assigned students, resolves pending items with the owner and refers decisions beyond its scope to administration. Escalate safeguarding concerns immediately through the institutional procedure; do not investigate independently.', 'Pendiente cerrado o escalado, responsable informado y fecha de seguimiento.', 'Closed or escalated item, notified owner and follow-up date.'],
]

export default function ProcedimientoAtencion({ moduloId }) {
  const { idioma } = useIdioma()
  const es = idioma === 'es'
  if (!/^T(3|4|5|8)\./.test(moduloId) && moduloId !== 'T10.4') return null
  const indices = moduloId.startsWith('T3.') ? [1, 2] : moduloId.startsWith('T4.') ? [0, 1, 3] : moduloId.startsWith('T5.') ? [4, 5] : [0, 1, 2, 3, 4, 5]
  return <section className="rounded-2xl border border-teal/20 bg-white p-5 shadow-sm">
    <p className="text-sm font-bold uppercase text-teal">{es ? 'Aplicación práctica del módulo' : 'Practical application'}</p>
    <h2 className="mt-2 text-xl font-bold text-navy">{es ? 'Qué hacer, qué verificar y qué dejar registrado' : 'What to do, check and record'}</h2>
    <p className="mt-3 text-base leading-relaxed text-navy/70">{es ? 'Practica primero con un expediente ficticio. La atención real comienza después de un acuerdo de colaboración, asignación y autorización de acceso. Las etiquetas y permisos concretos se comprueban en el sistema vigente.' : 'Practice with a fictional record first. Real support begins after a collaboration agreement, assignment and access authorization. Check current system labels and permissions.'}</p>
    <ol className="mt-5 space-y-4">{indices.map(i => <li key={i} className="rounded-xl bg-cream p-4">
      <h3 className="text-lg font-bold text-navy">{i + 1}. {PASOS[i][es ? 0 : 1]}</h3>
      <p className="mt-2 text-base leading-relaxed text-navy/80">{PASOS[i][es ? 2 : 3]}</p>
      <p className="mt-3 text-base leading-relaxed text-teal"><b>{es ? 'Resultado de cierre: ' : 'Closing evidence: '}</b>{PASOS[i][es ? 4 : 5]}</p>
    </li>)}</ol>
    <p className="mt-4 rounded-xl bg-gold/15 p-4 text-base">{es ? 'Evidencia de la práctica: describe el caso ficticio, lo verificado, la acción, el mensaje a la familia, el pendiente y el próximo seguimiento. Guarda tu trabajo en la sección Evidencia del módulo, sin datos personales reales.' : 'Practice evidence: describe the fictional case, checks, action, family message, pending issue and next follow-up. Save your work in the module Evidence section, without real personal data.'}</p>
  </section>
}
